### ISSUE TITLE
No heart rate data in list of streams

### ISSUE THREAD

**Issue by UtharaKeerthan** [Munroe-Meyer-Institute-VR-Laboratory/pyEmpatica#2]
Why there is no heart rate data from the list of streams you have mentioned in line 41 in empaticae4.py file.
I can see from the official empatica website that the heartrate data is also available in real time.

**Comment by wsarce** [comment]
Hi @UtharaKeerthan, this library was primarily developed for cometrics which has a live heart rate monitor from the E4.  You can see the connection code [here](https://github.com/Munroe-Meyer-Institute-VR-Laboratory/cometrics/blob/9125615955cac948ddab79959f3aadc08743af9f/output_view_ui.py#L1849).  You can see [here](https://github.com/Munroe-Meyer-Institute-VR-Laboratory/cometrics/blob/9125615955cac948ddab79959f3aadc08743af9f/output_view_ui.py#L1970) that the HR data is displayed on the user interface.  Additionally, you can see [here](https://github.com/Munroe-Meyer-Institute-VR-Laboratory/pyEmpatica/blob/45c05520908d814a91543bd17d4bda6fd554d98f/src/pyempatica/empaticae4.py#L227) that pyEmpatica does handle and expect HR data.

I believe that the HR data is subscribed to from either the IBI or BVP subscriptions.  Is there Empatica documentation saying you need to explicitly subscribe to that stream? Have you had issues receiving that data stream with pyEmpatica? I noticed that the HR data only updates when it has a good reading, so it is more intermittent than the other data streams.

**Comment by UtharaKeerthan** [comment]
Thanks for the response. I can compute the HR from the IBI intervals as mentioned in the empatica documentation.
